# Step 1: Build Stage (React App Tiari Kariba)
FROM node:18 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Step 2: Production Stage (Nginx Server re Chalaiba)
FROM nginx:alpine
# React build file ku Nginx folder ku aniba
COPY --from=build /app/dist /usr/share/nginx/html
# Port 80 open kariba
EXPOSE 80
# Server start kariba
CMD ["nginx", "-g", "daemon off;"]